### ISSUE TITLE
Result discrepancy between APIs

### ISSUE THREAD

**Issue by maghibus** [thingsboard/thingsboard#11619]
**Describe the bug**

It appears that the **Find Alarms by Query** API is not returning the correct number of results

I use Thingsboard CE 3.6.2

**To Reproduce**

1. you must have some alarm
2. using a tenant administrator

```
curl -X 'POST' \
  'https://localhost:443/api/alarmsQuery/find' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-Authorization: Bearer eyJhbGciOiJIUzUxMiJ...' \
  -d '{
  "entityFilter": {
    "type": "entityType",
    "resolveMultiple": true,
    "entityType": "DEVICE"
  },
  "keyFilters": [],
  "pageLink": {
    "page": 0,
    "pageSize": 10,
    "typeList": [
      "Allarme Flusso inverso"
    ],
    "statusList": [
      "ACTIVE"
    ]
  },
  "alarmFields": [
    {
      "type": "ALARM_FIELD",
      "key": "createdTime"
    },
    {
      "type": "ALARM_FIELD",
      "key": "type"
    },
    {
      "type": "ALARM_FIELD",
      "key": "severity"
    },
    {
      "type": "ALARM_FIELD",
      "key": "status"
    }
  ]
}
'
```

![image](https://github.com/user-attachments/assets/4b3ca6af-7353-4477-a48d-d2cbb3fc4bda)

the API returns only 3 items
**I would have expected to see 23 items**  as happens using the search panel or with the API **Get All Alarms V2**

**Screenshots**
![image](https://github.com/user-attachments/assets/be8ee8e7-e610-4456-b920-ecc808f803f8)

```
curl -X 'GET' \
  'https://localhost:443/api/v2/alarms?statusList=ACTIVE&severityList=MAJOR&typeList=Allarme%20Flusso%20inverso&pageSize=10&page=0' \
  -H 'accept: application/json' \
  -H 'X-Authorization: Bearer eyJ...'

```
![image](https://github.com/user-attachments/assets/9ff5297e-f643-4cbc-99ae-5f442a5a33f5)

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by sumin-denys** [comment]
Hi @maghibus,

I have checked this `api/alarmsQuery/find` endpoint locally and can confirm that everything is working correctly, so I guess this issue may be related to the misconfiguration.

Could you please add some details about your alarms, such as:

- Did all of your alarms have the same severity and status?
- Were these alarms created via **_Device Profile Node_** or **_Create Alarm Node_**?

Also, please confirm that both requests ran under the same Tenant Administrator.

The thingsboard.log file is required for any further investigation.

**Comment by maghibus** [comment]
Hi, thank you for your reply.
Below are the answers to your questions.

- The alarms do not have the same status or the same level of severity, and they are of various types.
![image](https://github.com/user-attachments/assets/5d1beb2d-2972-4164-a027-8548ab8e272d)

- The alarms are created through the Device Profile Node.
- Both requests run with the same tenant administrator.

**Comment by sumin-denys** [comment]
Hi @maghibus,

In this case, please try to change the  **"severityList"** as the following: 
```
"severityList": [
      "CRITICAL",
      "MAJOR",
      "MINOR",
      "WARNING",
      "INDETERMINATE"
]
```
Also, add the following array to your request:
```
"statusList": [
      "ANY"
]
```

Let me know if you need additional help.

**Comment by maghibus** [comment]
Sorry, I may not have understood your question well. In general, in the database, I have various types of events with different severities or statuses. However, I am interested in filtering only a certain subset of these messages. Specifically, I need the list of:

- type: "Allarme Flusso inverso"
- status : Active
- severity: ANY

Using API , I get 19 results
![image](https://github.com/user-attachments/assets/351ff46c-ca9a-402f-bec4-8b7f393a65c9)

while with query,  I get 3.
![image](https://github.com/user-attachments/assets/199161ad-d9ad-4576-b73a-c6e2723413d5)

**Comment by maghibus** [comment]
Sure! Feel free to share whatever you’d like me to see.

19 results
![image](https://github.com/user-attachments/assets/5bc0116a-a5b9-4c51-bad5-740e8ec574b3)

3 results
![image](https://github.com/user-attachments/assets/a2ff2cd7-5a7b-48d5-919a-f7938a4d5b00)

**Comment by sumin-denys** [comment]
Hi @maghibus,

Could you please increase the "pageSize" from 20 to, for example, 50?

Also, please run both queries and send thingsboard.log file in order to find the root cause of this problem.

**Comment by sumin-denys** [comment]
@maghibus,

Could you please provide the result of the following query:
```
{
  "entityFilter": {
    "type": "entityType",
    "resolveMultiple": true,
    "entityType": "DEVICE"
  },
   "pageLink": {
    "page": 0,
    "pageSize": 150,
    "sortOrder": {
      "direction": "ASC"
    }
  }
}
```
Here is the endpoint: ```/api/entitiesQuery/find```

**Comment by sumin-denys** [comment]
Hi @maghibus,

After consulting with the developer, the problem may be related to the problem with the database query that this endpoint builds. Could you please add a few fields that ThingsBoard will use to create the query for the database?

Here is the list of fields that should resolve this problem:
- **_startTs_** - this value shows the start of the time window from which alarms will be searched.
- **_endTs_** - the value represents the end of the time window within which alarms will be searched.
- **_timeWindow_** - should be the same as the endTs.

Below, I have added the example that you can use:
```
{
  "entityFilter": {
    "type": "entityType",
    "resolveMultiple": true,
    "entityType": "DEVICE"
  },
  "keyFilters": [],
  "pageLink": {
    "page": 0,    
    "pageSize": 150,
    "startTs": 0,
    "endTs": 1727460734,
    "timeWindow": 1727460734,
    "typeList": [
      "Allarme Flusso inverso"
    ],
    "statusList": [
        "ACTIVE"
    ]
  },
  "alarmFields": [
    {
      "type": "ALARM_FIELD",
      "key": "createdTime"
    },
    {
      "type": "ALARM_FIELD",
      "key": "type"
    },
    {
      "type": "ALARM_FIELD",
      "key": "severity"
    },
    {
      "type": "ALARM_FIELD",
      "key": "status"
    }
  ]
}
```

Please note that you should change the **endTs** and **timeWindow** values when you will run this query.

**Comment by maghibus** [comment]
Hi @sumin-denys ,
I had already tried configuring the timeWindow without any benefit. I just tried again with your suggestion, but the result is still incorrect.


![image](https://github.com/user-attachments/assets/75fdc55d-8b99-423b-ab86-1f060b0e399a)


![image](https://github.com/user-attachments/assets/d501e33a-a93a-4096-b2aa-be941e3a293d)

**Comment by sumin-denys** [comment]
Hi @maghibus,

Could you please run some queries for me again?

Here is an example of the request that you should run with different parameters:
```
{
  "entityFilter": {
  "type": "singleEntity",
  "singleEntity": {
    "id": "INSERT_HERE_DEVICE_ID_WITH_ALARM",
    "entityType": "DEVICE"
  }
  },
    "keyFilters": [],
    "pageLink": {
    "page": 0,
    "pageSize": 1000,
    "statusList": [
      "ACTIVE"
    ],
       "typeList": [
      "Allarme Flusso inverso"
    ],
    "startTs": 0,
    "endTs": 1727509752000,
    "timeWindow": 1727509752000
  },
    "alarmFields": [
    {
      "type": "ALARM_FIELD",
      "key": "createdTime"
    },
    {
      "type": "ALARM_FIELD",
      "key": "type"
    },
    {
      "type": "ALARM_FIELD",
      "key": "severity"
    },
    {
      "type": "ALARM_FIELD",
      "key": "status"
    }
  ]
}
```
Here is the list of id's that you can use:
- ad5220b0-9e5a-11ee-9f52-d3a185cf278a
- 97c24d50-9e5b-11ee-a698-dd11c0d72691
- bb91ad80-9103-11ee-825f-15097f9ba94d
- cd778060-cb05-11ee-bc6d-dfa875ec3888

I don't need a JSON file as a response. Please add screenshot results of these queries.

**Comment by maghibus** [comment]
Hi @sumin-denys, no problem 
below are the results of the queries.

![image](https://github.com/user-attachments/assets/c4f790ff-f9a5-41eb-89fd-c59a8ae94b54)

![image](https://github.com/user-attachments/assets/628ec40c-2b93-41d3-8d37-adf35a665555)

![image](https://github.com/user-attachments/assets/228d64f9-57bd-4889-ab9b-6d374dc22af5)

![image](https://github.com/user-attachments/assets/208ecd40-1461-4887-9052-47a19c5644b9)

**Comment by sumin-denys** [comment]
Hi @maghibus,

I found the reason for this behavior. The endpoint is working correctly, but the REST API Call returns only some of the alarms that the server can find. This is because the server is looking for active alarms only on the first 10,000 devices (the default value of this TB_SERVER_WS_MAX_ENTITIES_PER_ALARM_SUBSCRIPTION  environment variable). 

In your ThingsBoard instance, you already have 39,405 devices, so you need to increase the value of this parameter, and everything should work properly!

Here is an article that explains how you can change the values of the parameters: [How to change configuration parameters](https://thingsboard.io/docs/user-guide/install/how-to-change-config/)
