### ISSUE TITLE
[Bug] Rule chain rest api call can't work in 3.2.1

### ISSUE THREAD

**Issue by Krong1997** [thingsboard/thingsboard#4033]
**Describe the bug**
Rule chain rest api call can't work.

**Your Server Environment**

* own setup
  * Docker
  * ThingsBoard 3.2.1
  * LINUX 20.04 LTS

**To Reproduce**
1. Go to 'Root rule chain'
2. Add rest api call node
3. Add device
4. Post telemetry data
5. See error

**Expected behavior**
Under normal conditions, this rule can send rest API to other service.
In ThingsBoard 3.2.1, rest api call node can not work.
But we use ThingsBoard 3.2.0, rest api call node can work.

**Screenshots**
Rest api node configs 
![Screenshot from 2021-02-01 15-53-58](https://user-images.githubusercontent.com/71483852/106429921-15525c80-64a6-11eb-899f-1d7eccab2e40.png)
Root rule chain
![Screenshot from 2021-02-01 15-53-41](https://user-images.githubusercontent.com/71483852/106429869-04095000-64a6-11eb-9d40-dc0d9de242fe.png)
After post telemetry, event log always not found.
![Screenshot from 2021-02-01 15-53-34](https://user-images.githubusercontent.com/71483852/106429888-0a97c780-64a6-11eb-84eb-f84bb14e9334.png)

rule engine logs
```bash
2021-02-01 07:38:53,063 [tb-rule-engine-notifications-consumer-22-thread-1] INFO  o.t.s.s.q.p.AbstractConsumerService - [87b90620-6460-11eb-9429-47ae15c76b2a][TENANT][87b90620-6460-11eb-9429-47ae15c76b2a] Received Lifecycle event: CREATED
2021-02-01 07:38:53,269 [ForkJoinPool-8-worker-0] INFO  o.t.server.actors.tenant.TenantActor - [87b90620-6460-11eb-9429-47ae15c76b2a] Starting tenant actor.
2021-02-01 07:38:53,317 [ForkJoinPool-8-worker-0] INFO  o.t.server.actors.tenant.TenantActor - [87b90620-6460-11eb-9429-47ae15c76b2a] Going to init rule chains
2021-02-01 07:38:53,350 [ForkJoinPool-8-worker-0] INFO  o.t.server.actors.tenant.TenantActor - [87b90620-6460-11eb-9429-47ae15c76b2a] Tenant actor started.
2021-02-01 07:39:39,293 [tb-rule-engine-notifications-consumer-22-thread-1] INFO  o.t.s.s.q.p.AbstractConsumerService - [87b90620-6460-11eb-9429-47ae15c76b2a][RULE_CHAIN][87fa54e0-6460-11eb-9429-47ae15c76b2a] Received Lifecycle event: UPDATED
2021-02-01 07:39:39,437 [ForkJoinPool-10-worker-0] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|a3bb2100-6460-11eb-9429-47ae15c76b2a] Failed to init actor, attempt 1, going to retry in attempts in 5000ms
2021-02-01 07:39:42,282 [queue-scheduler-11-thread-1] INFO  o.t.s.q.u.DefaultTbApiUsageClient - Report statistics for: 1 tenants
2021-02-01 07:39:44,453 [ForkJoinPool-10-worker-3] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|a3bb2100-6460-11eb-9429-47ae15c76b2a] Failed to init actor, attempt 2, going to retry in attempts in 10000ms
2021-02-01 07:39:50,875 [TB-Scheduling-3] INFO  o.t.s.s.q.TbRuleEngineConsumerStats - [Main] Stats: totalMsgs = [1] successfulMsgs = [1] timeoutMsgs = [0] failedMsgs = [0] tmpTimeout = [0] tmpFailed = [0] successfulIterations = [1] failedIterations = [0] 
2021-02-01 07:39:54,464 [ForkJoinPool-10-worker-2] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|a3bb2100-6460-11eb-9429-47ae15c76b2a] Failed to init actor, attempt 3, going to retry in attempts in 15000ms
2021-02-01 07:39:55,754 [sql-log-5-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-3 [TS Latest] queueSize [0] totalAdded [6] totalSaved [6] totalFailed [0]
2021-02-01 07:39:57,677 [tb-rule-engine-notifications-consumer-22-thread-1] INFO  o.t.s.s.q.p.AbstractConsumerService - [87b90620-6460-11eb-9429-47ae15c76b2a][DEVICE_PROFILE][aebf4220-6460-11eb-9429-47ae15c76b2a] Received Lifecycle event: CREATED
2021-02-01 07:39:57,987 [tb-rule-engine-notifications-consumer-22-thread-1] INFO  o.t.s.s.q.p.AbstractConsumerService - [87b90620-6460-11eb-9429-47ae15c76b2a][DEVICE][aedf7450-6460-11eb-9429-47ae15c76b2a] Received Lifecycle event: CREATED
2021-02-01 07:40:00,835 [TB-Scheduling-2] INFO  o.t.s.d.n.CassandraBufferedRateExecutor - Permits queueSize = [0] totalAdded = [12] totalLaunched = [12] totalReleased = [12] totalFailed = [0] totalExpired = [0] totalRejected = [0] totalRateLimited = [0] totalRateLimitedTenants = [0] currBuffer = [0] 
2021-02-01 07:40:02,283 [queue-scheduler-11-thread-1] INFO  o.t.s.q.u.DefaultTbApiUsageClient - Report statistics for: 1 tenants
2021-02-01 07:40:09,475 [ForkJoinPool-10-worker-2] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|a3bb2100-6460-11eb-9429-47ae15c76b2a] Failed to init actor, attempt 4, going to retry in attempts in 20000ms
2021-02-01 07:40:29,512 [ForkJoinPool-10-worker-3] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|a3bb2100-6460-11eb-9429-47ae15c76b2a] Failed to init actor, attempt 5, going to retry in attempts in 25000ms
2021-02-01 07:40:51,187 [TB-Scheduling-1] INFO  o.t.s.s.q.TbRuleEngineConsumerStats - [Main] Stats: totalMsgs = [1] successfulMsgs = [1] timeoutMsgs = [0] failedMsgs = [0] tmpTimeout = [0] tmpFailed = [0] successfulIterations = [1] failedIterations = [0] 
2021-02-01 07:40:54,526 [ForkJoinPool-10-worker-1] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|a3bb2100-6460-11eb-9429-47ae15c76b2a] Failed to init actor, attempt 6, going to retry in attempts in 30000ms
2021-02-01 07:40:55,754 [sql-log-5-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-3 [TS Latest] queueSize [0] totalAdded [6] totalSaved [6] totalFailed [0]
2021-02-01 07:41:00,837 [TB-Scheduling-2] INFO  o.t.s.d.n.CassandraBufferedRateExecutor - Permits queueSize = [0] totalAdded = [6] totalLaunched = [6] totalReleased = [6] totalFailed = [0] totalExpired = [0] totalRejected = [0] totalRateLimited = [0] totalRateLimitedTenants = [0] currBuffer = [0] 
2021-02-01 07:41:02,284 [queue-scheduler-11-thread-1] INFO  o.t.s.q.u.DefaultTbApiUsageClient - Report statistics for: 1 tenants
2021-02-01 07:41:15,911 [tb-rule-engine-notifications-consumer-22-thread-1] INFO  o.t.s.s.q.p.AbstractConsumerService - [87b90620-6460-11eb-9429-47ae15c76b2a][RULE_CHAIN][87fa54e0-6460-11eb-9429-47ae15c76b2a] Received Lifecycle event: UPDATED
2021-02-01 07:41:22,285 [queue-scheduler-11-thread-1] INFO  o.t.s.q.u.DefaultTbApiUsageClient - Report statistics for: 1 tenants
2021-02-01 07:41:24,536 [ForkJoinPool-10-worker-2] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|a3bb2100-6460-11eb-9429-47ae15c76b2a] Failed to init actor, attempt 7, going to retry in attempts in 35000ms
2021-02-01 07:41:51,202 [TB-Scheduling-1] INFO  o.t.s.s.q.TbRuleEngineConsumerStats - [Main] Stats: totalMsgs = [1] successfulMsgs = [1] timeoutMsgs = [0] failedMsgs = [0] tmpTimeout = [0] tmpFailed = [0] successfulIterations = [1] failedIterations = [0] 
2021-02-01 07:41:55,754 [sql-log-5-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-3 [TS Latest] queueSize [0] totalAdded [6] totalSaved [6] totalFailed [0]
2021-02-01 07:41:59,544 [ForkJoinPool-10-worker-3] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|a3bb2100-6460-11eb-9429-47ae15c76b2a] Failed to init actor, attempt 8, going to retry in attempts in 40000ms
2021-02-01 07:42:00,838 [TB-Scheduling-3] INFO  o.t.s.d.n.CassandraBufferedRateExecutor - Permits queueSize = [0] totalAdded = [6] totalLaunched = [6] totalReleased = [6] totalFailed = [0] totalExpired = [0] totalRejected = [0] totalRateLimited = [0] totalRateLimitedTenants = [0] currBuffer = [0] 
2021-02-01 07:42:02,287 [queue-scheduler-11-thread-1] INFO  o.t.s.q.u.DefaultTbApiUsageClient - Report statistics for: 1 tenants
2021-02-01 07:42:39,613 [ForkJoinPool-10-worker-0] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|a3bb2100-6460-11eb-9429-47ae15c76b2a] Failed to init actor, attempt 9, going to retry in attempts in 45000ms
2021-02-01 07:43:02,289 [queue-scheduler-11-thread-1] INFO  o.t.s.q.u.DefaultTbApiUsageClient - Report statistics for: 1 tenants
2021-02-01 07:43:24,668 [ForkJoinPool-10-worker-3] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|a3bb2100-6460-11eb-9429-47ae15c76b2a] Failed to init actor, attempt 10, going to stop attempts.
org.thingsboard.server.actors.TbActorException: Failed to init actor
        at org.thingsboard.server.actors.service.ComponentActor.initProcessor(ComponentActor.java:71)
        at org.thingsboard.server.actors.service.ComponentActor.init(ComponentActor.java:56)
        at org.thingsboard.server.actors.TbActorMailbox.tryInit(TbActorMailbox.java:61)
        at org.thingsboard.server.actors.TbActorMailbox.lambda$null$1(TbActorMailbox.java:77)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException: null
        at org.thingsboard.rule.engine.rest.TbHttpClient.<init>(TbHttpClient.java:145)
        at org.thingsboard.rule.engine.rest.TbRestApiCallNode.init(TbRestApiCallNode.java:54)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:151)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:63)
        at org.thingsboard.server.actors.service.ComponentActor.initProcessor(ComponentActor.java:62)
        ... 8 common frames omitted
```

**Comment by vvlladd28** [comment]
Hi @Krong1997,
We have added a fix in the master branch.
You need to make a new build from the master branch or delete the rule node from the Rule Chain and add it again.

**Comment by Krong1997** [comment]
We try merge master to release 3.2. This bug is resolved. Thanks~

**Comment by Manusisko** [comment]
What about 3.2.1PE version is there a fix for this issue??

**Comment by vvlladd28** [comment]
Hi @Manusisko , will be fixed in version 3.3

**Comment by Manusisko** [comment]
> Hi @Manusisko , will be fixed in version 3.3

Can you guys provide a working JAR file containing a fixed node for the rest api call node? We've got several running rule chains that depend on it to work!!

I've tried compiling the one in the master repo, succeeded in doing so but the problem persists
